### ISSUE TITLE
CircleCI migration and improvements

### ISSUE THREAD

**Issue by ThePeach** [buildit/gravy#20]
Opening this ticket as a way to decide and define the functionality for CircleCI, and more generally, for the pipeline.

The first item of the list would be to move it to circleCi 2.0

While at it some improvements should be done, specifically by running linting and tests on every PR and add a step for automatically releasing it on tag creation (so effectively you don't have to do the release process manually which can be a bit boring)

**Comment by james-nash** [comment]
Closing this as work on Gravy will no longer happen in this repo. It moved to: https://github.com/ThePeach/gravy
